site_name: Boise State Research Computing
nav:
  - Home: 'index.md'
  - 'Cluster Guide':
    - 'getting_an_account.md'
    - 'logging_in.md'
    - 'transferring_files.md'
    - 'storing_data.md'
    - 'loading_software.md'
    - 'scheduling.md'
    - 'interactive_sessions.md'
    - 'open_ondemand.md'
    - 'faq.md'
    - 'hpc_resources.md'
  - 'Software Specific Guides':
    - 'software/conda.md'
    - 'software/julia.md'
    - 'software/r.md'
    - 'software/abyss.md'
    - 'software/alphafold.md'
    - 'software/gromacs.md'
    - 'software/matlab.md'
    - 'software/moose.md'
    - 'software/quantumespresso.md'
    - 'software/vasp.md'
    - 'software/apptainer.md'
    - 'software/c.md'
  - 'Resources':
    - 'training.md'
    - 'linux.md'
    - 'glossary.md'
theme:
  name: material
  logo: images/boisestate-B-1color-orange-rgb.png
  favicon: images/boisestate-B-1color-orange-rgb.png
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:researchcomputing@boisestate.edu
      name: researchcomputing@boisestate.edu
copyright: <b>Research Computing</b><br>Riverfront Hall, Suite 319, 1987 W Cesar Chavez Ln, Boise, ID 83725<hr>
markdown_extensions:
  - attr_list
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - codehilite
  - pymdownx.arithmatex:
      generic: true
